language: r
r:
  - oldrel
  - release

# Be strict when checking our package
warnings_are_errors: false

# Sudo is required
sudo: true

# Use trusty distribution of linux
dist: trusty

# Use both linux and osx operating systems
os:
  - linux
  - osx

# Use cache for packages
cache:
  apt: true
  packages: true

# System dependencies for HTTP calling
addons:
  apt:
    packages:
      - libgit2-dev
      - libcurl4-openssl-dev
      - libxml2-dev

script:
  - travis_wait 30 R CMD build .

r_binary_packages:
  - testthat

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
