language: r
sudo: false

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

# Use cache for packages
cache:
  apt: true
  packages: true
  ccache: true

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    # Linux + g++-7
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - gfortran-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir -p ~/.R/
  - echo "CC = $CC" >> ~/.R/Makevars
  - echo "CXX = ${CXX} -fPIC " >> ~/.R/Makevars
  - echo "CXX14 = ${CXX} -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

install:
  - R -e 'install.packages("devtools", quiet = T)' -e 'devtools::install_deps(dep = T, quiet = T)'

script:
  - travis_wait 42 R CMD build .
  - travis_wait 59 R CMD check hBayesDM*.tar.gz --as-cran

r_binary_packages:
  - testthat

# r_github_packages:
#   - r-lib/covr

# after_success:
#   - Rscript -e 'covr::codecov()'

after_failure:
  - cat rstanarm.Rcheck/00*
